baseURL = 'https://domcorvasce.com/'
languageCode = 'en-us'
title = 'Domenico Corvasce'
theme = 'typo'

[params]
description = 'My personal website'

theme = 'light'
colorPalette = 'default'
hideHeader = false

homeIntroTitle = 'Hello there!'
homeIntroContent = """
Nice to meet you, my name is Domenico. I am a Software Engineer interested in database systems, distributed systems, and systems performance optimization.

I am based in Italy where I work at [Prima Assicurazioni](https://helloprima.com) on systems integration.

All opinions are my own.
"""

homeCollectionTitle = 'Posts'
homeCollection = 'posts'

paginationSize = 100
listSummaries = true
listDateFormat = 'Jan 2, 2006'

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/domcorvasce/"

[[params.social]]
name = "github"
url = "https://github.com/domcorvasce"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[markup]
[markup.highlight]
style = 'algol'

[caches]
[caches.images]
dir = ':cacheDir/images'

[[module.mounts]]
source = 'images'
target = 'static/images'
